FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
EXPOSE 80
ENTRYPOINT ["dotnet", "ProductApi.dll"]